#!/usr/bin/env python
import os
import datetime

default = "No Value Set"

body = """<html>
<head>
<title>Lab 3 - WSGI experiments</title>
</head>
<body>
<p>Hey there, this page has been generated by {software}, running at {path}</p>
<p>Today is {month} {date}, {year}.</p>
<p>This page was requested by IP Address {client_ip}</p>
</body>
</html>"""


def application(environ, start_response):
    import pprint
    pprint.pprint(environ)

    path = os.environ.get('SCRIPT_NAME', __name__)
    month = datetime.datetime.now().strftime('%B')
    year = datetime.datetime.now().year
    date = datetime.datetime.now().date
    client_ip = environ.get('REMOTE_ADDR', 'eeee')


    response_body = body.format(
        software=environ.get('SERVER_SOFTWARE', default),
        path=path,
        month=month,
        date=date,
        year=year,
        client_ip=client_ip
    )
    status = '200 OK'

    response_headers = [('Content-Type', 'text/html'),
                        ('Content-Length', str(len(response_body)))]
    start_response(status, response_headers)

    return [response_body.encode('utf8')]


if __name__ == '__main__':
    from wsgiref.simple_server import make_server
    srv = make_server('localhost', 8080, application)
    srv.serve_forever()
